### ISSUE TITLE
Mann-Whitney test bug

### ISSUE THREAD

**Issue by jcamunas** [iosonofabio/singlet#2]
Mann-Whitney test has now two conditions to test for degenerate cases to avoid test breaking due to ties. The first condition tests for all values in each distribution being exactly the same, for such a case a p-value=1 is reported. This causes a problem for genes not seen in one distribution (all 0, or -1 in logscale) and expressed in the other distribtution, which should have low p-value and should not break the test. As the Mann Whitney test is done in the union dataset i think it would be enough to check the condtion for the union dataset. So something like:
if (len(np.unique(np.concatenate((co1.values,co2.values),axis=0) ) ==1 ):

instead of current:

 if ((len(np.unique(co1.values)) == 1) or (len(np.unique(co2.values)) == 1))

This should not break the test and p-values for genes seen in one dataset and not in the other one would be reported.

I think that in that case the second condition tested to break ties might not be needed either (check that all ranked values are not identyical for both distributions), as scipy.mannwhitneyu seems to account for it and gives a p-value~0.5 as it's tie corrected. Still might be a good think to keep just in case.

**Comment by iosonofabio** [comment]
Addressed in f22a84aaa66a5538a48ae93e13ab3b0fdb71648f, should work now
