### ISSUE TITLE
query using @ in samplesheet

### ISSUE THREAD

**Issue by jcamunas** [iosonofabio/singlet#3]
Query samples by metadata does not take local variables using the @ sign as explained in http://pandas.pydata.org/pandas-docs/version/0.15.0/generated/pandas.DataFrame.query.html

Example:
donorlist = ['R231', 'R236', 'R240', 'R241', 'R244']
ds_dummy_counts.samplesheet.query('DonorID == @donorlist')  
##this retrieves list of samples where DonorID is in donorlist

ds_dummy_counts.query_samples_by_metadata('DonorID == @donorlist')
## this throws a key error (KeyError: 'donorlist'), as if it could not see the list

**Comment by iosonofabio** [comment]
This works, use the `local_dict` argument. Closing.
